### ISSUE TITLE
Switch to starship?

### ISSUE THREAD

**Issue by mrolli** [mrolli/dotfiles#30]
**Is your feature request related to a current shortcoming? Please describe.**
While oh-my-posh works as expected and I've done two themes for it, it still bothers me that is has daily new versions. Starship seems to be replacement in Rust with a lot of modules. Could be a viable alternative. The current features I use of omp must be available again as I consider them the bear minimum.

**Describe the solution you'd like**
Decide if switching to starship might be a good idea. See https://starship.rs/guide/

**Comment by JanDeDobbeleer** [comment]
@mrolli I'm interested to understand how pushing fixes/features is a bad experience. The way I see this, but I'm biased probably, is that you do not need to update every time a new version is out, keep your own pace 😄

**Comment by mrolli** [comment]
@JanDeDobbeleer It's more a matter of personal taste. Your project makes a release on almost every commit. There are days with up to 5 releases. That means, whenever I run `brew upgrade` I have for use an update of omp. Sure, I could pin and only update every now and then, but that lacks a trigger. I'm not a big fan of pinning.

I prefer a release style like the GH cli/cli tool has, another project in Go I use and like very much. They make about biweekly releases with pretty release notes separated in fixes and new features in case of minor releases, i.e. for [2.10.0](https://github.com/cli/cli/releases/tag/v2.10.0). 
I'm one of these release notes readers and appreciate them. Every second week I invest 5min of my time to study their release notes. With your release style I definitely miss new features as I never look into the code base.

But as I said, that's pretty much only a matter of personal taste. And I'm also not about to switch. I have never looked into starship yet, it just popped up in severals users dotfiles lately and this ticket is just a reminder to once have a look into it. 

Beside that, your project does a very good job, so no urge to leave or even leave at all.

**Comment by JanDeDobbeleer** [comment]
@mrolli on the topic of release notes, maybe the new [blog](https://ohmyposh.dev/blog/whats-new-3) is something you would like to read?
